name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Create .env File
      run: |
        touch .env
        echo VITE_APP_SUPABASE_URL=${VITE_APP_SUPABASE_URL} >> .env
        echo VITE_APP_SUPABASE_ANON_KEY=${VITE_APP_SUPABASE_ANON_KEY} >> .env
        echo VITE_APP_EDGE_URL=${VITE_APP_EDGE_URL} >> .env
        echo VITE_APP_EDGE_API_KEY=${VITE_APP_EDGE_API_KEY} >> .env
        echo VITE_APP_APPLICATION_URL=${VITE_APP_APPLICATION_URL} >> .env
        echo VITE_APP_ENVIRONMENT=${VITE_APP_ENVIRONMENT} >> .env
        cat .env
      env: 
        VITE_APP_SUPABASE_URL: ${{ secrets.VITE_APP_SUPABASE_URL }} 
        VITE_APP_SUPABASE_ANON_KEY: ${{ secrets.VITE_APP_SUPABASE_ANON_KEY }} 
        VITE_APP_EDGE_URL: ${{ secrets.VITE_APP_EDGE_URL }} 
        VITE_APP_EDGE_API_KEY: ${{ secrets.VITE_APP_EDGE_API_KEY }} 
        VITE_APP_APPLICATION_URL: ${{ secrets.VITE_APP_APPLICATION_URL }} 
        VITE_APP_ENVIRONMENT: ${{ secrets.VITE_APP_ENVIRONMENT }} 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --global yarn
    - name: Install Packages
      run: yarn install
    - run: yarn build
    - name: Create Archive
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r snapshot.zip dist
    - name: Upload Archive as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: snapshot.zip
        path: snapshot.zip
