name: Build & Release

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
    paths-ignore:
      - '.github/**/*.yml'
      - '.gitignore'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Create .env File
      run: |
        touch .env
        echo VITE_APP_SUPABASE_URL=${VITE_APP_SUPABASE_URL} >> .env
        echo VITE_APP_SUPABASE_ANON_KEY=${VITE_APP_SUPABASE_ANON_KEY} >> .env
        echo VITE_APP_EDGE_URL=${VITE_APP_EDGE_URL} >> .env
        echo VITE_APP_EDGE_API_KEY=${VITE_APP_EDGE_API_KEY} >> .env
        echo VITE_APP_APPLICATION_URL=${VITE_APP_APPLICATION_URL} >> .env
        echo VITE_APP_ENVIRONMENT=${VITE_APP_ENVIRONMENT} >> .env
        cat .env
      env: 
        VITE_APP_SUPABASE_URL: ${{ secrets.VITE_APP_SUPABASE_URL }} 
        VITE_APP_SUPABASE_ANON_KEY: ${{ secrets.VITE_APP_SUPABASE_ANON_KEY }} 
        VITE_APP_EDGE_URL: ${{ secrets.VITE_APP_EDGE_URL }} 
        VITE_APP_EDGE_API_KEY: ${{ secrets.VITE_APP_EDGE_API_KEY }} 
        VITE_APP_APPLICATION_URL: ${{ secrets.VITE_APP_APPLICATION_URL }} 
        VITE_APP_ENVIRONMENT: ${{ secrets.VITE_APP_ENVIRONMENT }} 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --global yarn
    - name: Install Packages
      run: yarn install
    - run: yarn build
    - name: Create Archive
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r extension-artifact.zip dist
    - name: Upload Archive as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: extension-artifact
        path: extension-artifact.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Archive Artifact
        uses: actions/download-artifact@v3
        with:
          name: extension-artifact
      - run: ls -R
      - name: Generate Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          configuration: ".github/config/configuration.json"
          ignorePreReleases: ${{ !contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          files: extension-artifact
        env:
          GITHUB_REPOSITORY: my_gh_org/my_gh_repo
