name: 'Pull Request'
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Automate Pull Request
        uses: lucajoos/pull-request-issue-automation@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          author: (lucajoos)